import os
import sqlite3
import json
import argparse
from datetime import datetime, timedelta
from dotenv import load_dotenv
import google.generativeai as genai

# Local Imports
from audio_generator import AudioGenerator
from video_renderer import render_briefing_video
# YouTubeUploader is imported lazily to avoid dependency errors if libs are missing

# Load environment variables
load_dotenv()

# Configure Gemini
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

DB_PATH = "news.db"

def get_recent_articles(hours=24, limit=10):
    """Fetches key articles from the last N hours."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Calculate cutoff time
    cutoff = (datetime.now() - timedelta(hours=hours)).isoformat()
    
    # Select high-signal articles (non-null summary fields)
    query = '''
        SELECT slug, title, gist, why_it_matters, key_details, source, published_at
        FROM articles
        WHERE published_at >= ? 
        ORDER BY published_at DESC
    '''
    cursor.execute(query, (cutoff,))
    rows = cursor.fetchall()
    conn.close()
    
    articles = []
    for r in rows:
        articles.append({
            "slug": r[0],
            "title": r[1],
            "gist": r[2],
            "impact": r[3],
            "details": r[4],
            "source": r[5],
            "published": r[6]
        })
    
    print(f"Found {len(articles)} articles from the last {hours} hours.")
    return articles[:limit]

def generate_briefing_script(articles):
    """Generates a cohesive 6-7 minute podcast script."""
    if not articles:
        print("No articles available for briefing.")
        return None

    # Prepare context
    context = ""
    for idx, art in enumerate(articles):
        context += f"\nITEM {idx+1}: {art['title']}\n"
        context += f"Source: {art['source']}\n"
        context += f"Summary: {art['gist']}\n"
        context += f"Impact: {art['impact']}\n"
        context += f"Details: {art['details']}\n"
        context += "-" * 30

    prompt = f"""
    You are the producer of "Daily AI Wire", a premium daily intelligence podcast for AI professionals.
    Your task is to write a **dialogue script** for two hosts:
    *   **HOST A (Marcus):** Analytic, skeptical, focuses on technical details and "the bear case".
    *   **HOST B (Sarah):** Enthusiastic, visionary, focuses on the big picture and "the bull case".

    TONE: Professional banter. Fast-paced, high-energy, like a top-tier tech radio show. 
    Use "Host A:" and "Host B:" tags for every line.

    STRUCTURE:
    1. **The Hook** (0:00-0:45): Start with the single most important story. Grab attention immediately.
    2. **The Deep Dive** (0:45-3:30): Discuss the top 2-3 stories. Have them debate/discuss the implications.
    3. **The Rapid Fire** (3:30-5:30): Sarah lists headlines, Marcus gives a 1-sentence punchy take on each.
    5. **Outro** (6:30-Finish): Sign off. 
       - **MANDATORY:** Ask listeners to "Subscribe to Daily AI Wire" (YouTube/Podcast).
       - **MANDATORY TRANSPARENCY:** Host A or B must explicitly state: "As always, Daily AI Wire is generated by AI and curated for humans." regarding the content/voices.
       - Final line: "Stay intelligent."

    CONSTRAINTS:
    - Target: ~1000-1100 words total (7-8 mins).
    - **HARD LIMIT:** Must result in LESS THAN 9 MINUTES of audio.
    - **CRITICAL:** Format EVERY line as "Host A: [text]" or "Host B: [text]".
    - NO visual direction. NO music cues in text.
    - Write for the EAR: Short sentences, natural breathing points.
    
    INPUT DATA:
    {context}
    
    Write the dialogue script now.
    """

    model = genai.GenerativeModel("gemini-2.5-flash")
    print("Generating Daily Briefing Podcast Script...")
    
    try:
        response = model.generate_content(prompt)
        script = response.text
        # Cleanup markdown but keep Host tags
        script = script.replace('**', '').replace('##', '')
        return script
    except Exception as e:
        print(f"Error generating script: {e}")
        return None

def save_script(script):
    """Saves the script to a file for review/audio gen."""
    filename = f"briefing_script_{datetime.now().strftime('%Y-%m-%d')}.txt"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(script)
    print(f"Script saved to {filename}")
    return filename

def run_daily_briefing(upload=False):
    print("🚀 Starting Daily Video Briefing Pipeline...")
    
    # 1. Fetch Articles
    articles = get_recent_articles(hours=24, limit=8)
    if not articles:
        print("❌ Not enough news to generate a briefing.")
        return

    # 2. Generate Script
    script = generate_briefing_script(articles)
    if not script:
        return
    save_script(script)

    # 3. Generate Audio
    print("\n🎙️ Generating Podcast Audio (Banter Mode)...")
    audio_gen = AudioGenerator()
    # Use a specific slug for the daily show
    show_slug = f"daily_briefing_{datetime.now().strftime('%Y-%m-%d')}"
    
    # Use the new Podcast/Dialogue generator
    podcast_audio_path = audio_gen.generate_podcast_audio(show_slug, script)
    
    if not podcast_audio_path:
        print("⚠️ Audio generation failed (likely missing credentials).")
        print("ℹ️ Creating dummy silence audio for testing video render...")
        
        # Create a 5-second dummy audio file
        dummy_audio = "static/audio/dummy_silence.mp3"
        if not os.path.exists("static/audio"):
            os.makedirs("static/audio")
            
        try:
            # Simple silent file creation
            from moviepy import AudioClip
            silent_clip = AudioClip(lambda t: [0], duration=5, fps=44100) 
            silent_clip.write_audiofile(dummy_audio, fps=44100, logger=None)
            podcast_audio_path = f"/{dummy_audio}"
        except Exception as e:
            print(f"❌ Could not create dummy audio: {e}")
            return
        
    # Convert web path (/static/...) to local file path
    local_audio_path = podcast_audio_path.lstrip('/')
    if not os.path.exists(local_audio_path):
        print(f"❌ Audio file not found at: {local_audio_path}")
        return

    # 4. Render Video
    print("\n🎬 Rendering Video...")
    video_filename = f"daily_briefing_{datetime.now().strftime('%Y-%m-%d')}.mp4"
    
    # Priority: 1. Loops Folder (Multi-Clip), 2. background_loop.mp4 (Single), 3. Image Fallback
    background_template = "static/video/loops" 
    if not os.path.exists(background_template) or not os.listdir(background_template):
        background_template = "static/video/background_loop.mp4"
    
    # Extract headlines for Ticker
    headlines = [a['title'] for a in articles]
    
    video_success = render_briefing_video(local_audio_path, background_template, video_filename, headlines=headlines)
    
    if not video_success:
        print("❌ Video rendering failed.")
        return

    print(f"\n✅ Video ready: {video_filename}")

    # 5. Upload to YouTube
    if upload:
        print("\n☁️  Uploading to YouTube...")
        try:
            from youtube_uploader import YouTubeUploader
            uploader = YouTubeUploader()
            if uploader.youtube:
                title = f"Daily AI Wire: {articles[0]['title']} + Top Stories ({datetime.now().strftime('%B %d, %Y')})"
                description = (
                    f"Today's high-signal AI intelligence briefing.\n\n"
                    f"Featured Story: {articles[0]['title']}\n"
                    f"Full Briefing covering {len(articles)} key updates.\n\n"
                    f"🔔 Subscribe to Daily AI Wire for your daily intelligence download.\n\n"
                    f"DailyAIWire.news - Intelligence for the AI Age.\n"
                    f"Transparency: This content is generated by AI and curated for humans.\n\n"
                    f"#AI #TechNews #ArtificialIntelligence"
                )
                uploader.upload_video(video_filename, title, description)
            else:
                print("⚠️  Skipping upload: Authenticated service not available.")
        except ImportError:
            print("⚠️  Skipping upload: YouTubeUploader module missing or dependencies not installed.")
    else:
        print("ℹ️  Upload skipped (use --upload to publish).")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--upload", action="store_true", help="Upload to YouTube after generation")
    args = parser.parse_args()
    
    run_daily_briefing(upload=args.upload)
